# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  desc ""
  homepage ""
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  on_macos do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.7/cage_Darwin_x86_64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "431516cdb2a99acf026c5221c2c3852866675a3197ef89c6b0061fa00a32e7ca"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.7/cage_Darwin_arm64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "830111cd6b63a3c71961498397437968345e080b908cdda716c4383965122fce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.7/cage_Linux_x86_64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "b7b5ffabeb7c1e5be09d32a4598d5089a21cddbd51cfaa58cc42e1a8af78c5ff"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.7/cage_Linux_arm64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "f51d19be8f56cebee0b27040b30e96109e993e04865007e20096d9682c7fee15"
    end
  end

  # No zap stanza required
end
