# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  desc ""
  homepage ""
  version "0.1.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  on_macos do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.14/cage_Darwin_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "70da7087025b388bb70289fab93b0479ce85facef09acd4096aa75ee46347b6a"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.14/cage_Darwin_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "0e6f9c27f1d739968e7b3942991a1cb513ce323b870b5c62bad9d22014dbe953"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.14/cage_Linux_x86_64.tar.gz",
        using: :homebrew_curl
      sha256 "9106a24743bd7d9c631c37d0041bcb181fd80aaf2e2834530cc59386aeb4df26"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.14/cage_Linux_arm64.tar.gz",
        using: :homebrew_curl
      sha256 "6b7385af2ba2dc09c16d5fc2328b826c8ba3ba7a15c3820fa15085dc02b14778"
    end
  end

  # No zap stanza required
end
