# This file was generated by GoReleaser. DO NOT EDIT.
cask "cage" do
  desc ""
  homepage ""
  version "0.1.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cage"

  on_macos do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.11/cage_Darwin_x86_64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "dafc19d1f25c1763bc30c5f9d0c4a48b7282c083aa6c368dc2710e4f2bbe6cd9"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.11/cage_Darwin_arm64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "49a0b6961d327d00357bcbd1892a21d5f036cc17c4bc2c997225ed7be54643c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Warashi/cage/releases/download/v0.1.11/cage_Linux_x86_64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "649d70ba7dbad4afa4804462e49b417a81e514322a53b70f3706cc6a1677558a"
    end
    on_arm do
      url "https://github.com/Warashi/cage/releases/download/v0.1.11/cage_Linux_arm64.tar.gz",
        verified: "github.com/Warashi/cage/",
        using: :homebrew_curl
      sha256 "e9b91441a0eeb5f56bc1a72e6d96512028fa26caa7c633ed5f1266904a8995fd"
    end
  end

  # No zap stanza required
end
